/*
 * This file is generated by jOOQ.
 */
package com.jzy.order.db.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OrdersEntity implements Serializable {

    private static final long serialVersionUID = 305506008;

    private Long      id;
    private String    orderId;
    private Long      shopId;
    private String    uid;
    private String    userName;
    private Long      totalMoney;
    private String    remark;
    private Integer   status;
    private Timestamp ctime;
    private Timestamp mtime;

    public OrdersEntity() {}

    public OrdersEntity(OrdersEntity value) {
        this.id = value.id;
        this.orderId = value.orderId;
        this.shopId = value.shopId;
        this.uid = value.uid;
        this.userName = value.userName;
        this.totalMoney = value.totalMoney;
        this.remark = value.remark;
        this.status = value.status;
        this.ctime = value.ctime;
        this.mtime = value.mtime;
    }

    public OrdersEntity(
        Long      id,
        String    orderId,
        Long      shopId,
        String    uid,
        String    userName,
        Long      totalMoney,
        String    remark,
        Integer   status,
        Timestamp ctime,
        Timestamp mtime
    ) {
        this.id = id;
        this.orderId = orderId;
        this.shopId = shopId;
        this.uid = uid;
        this.userName = userName;
        this.totalMoney = totalMoney;
        this.remark = remark;
        this.status = status;
        this.ctime = ctime;
        this.mtime = mtime;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getOrderId() {
        return this.orderId;
    }

    public void setOrderId(String orderId) {
        this.orderId = orderId;
    }

    public Long getShopId() {
        return this.shopId;
    }

    public void setShopId(Long shopId) {
        this.shopId = shopId;
    }

    public String getUid() {
        return this.uid;
    }

    public void setUid(String uid) {
        this.uid = uid;
    }

    public String getUserName() {
        return this.userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    public Long getTotalMoney() {
        return this.totalMoney;
    }

    public void setTotalMoney(Long totalMoney) {
        this.totalMoney = totalMoney;
    }

    public String getRemark() {
        return this.remark;
    }

    public void setRemark(String remark) {
        this.remark = remark;
    }

    public Integer getStatus() {
        return this.status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }

    public Timestamp getCtime() {
        return this.ctime;
    }

    public void setCtime(Timestamp ctime) {
        this.ctime = ctime;
    }

    public Timestamp getMtime() {
        return this.mtime;
    }

    public void setMtime(Timestamp mtime) {
        this.mtime = mtime;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("OrdersEntity (");

        sb.append(id);
        sb.append(", ").append(orderId);
        sb.append(", ").append(shopId);
        sb.append(", ").append(uid);
        sb.append(", ").append(userName);
        sb.append(", ").append(totalMoney);
        sb.append(", ").append(remark);
        sb.append(", ").append(status);
        sb.append(", ").append(ctime);
        sb.append(", ").append(mtime);

        sb.append(")");
        return sb.toString();
    }
}
