/*
 * This file is generated by jOOQ.
 */
package com.jzy.order.db.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProductCategoryEntity implements Serializable {

    private static final long serialVersionUID = 825141197;

    private Long      id;
    private Long      shopId;
    private String    categoryName;
    private String    categoryDesc;
    private Integer   priority;
    private Timestamp ctime;
    private Timestamp mtime;

    public ProductCategoryEntity() {}

    public ProductCategoryEntity(ProductCategoryEntity value) {
        this.id = value.id;
        this.shopId = value.shopId;
        this.categoryName = value.categoryName;
        this.categoryDesc = value.categoryDesc;
        this.priority = value.priority;
        this.ctime = value.ctime;
        this.mtime = value.mtime;
    }

    public ProductCategoryEntity(
        Long      id,
        Long      shopId,
        String    categoryName,
        String    categoryDesc,
        Integer   priority,
        Timestamp ctime,
        Timestamp mtime
    ) {
        this.id = id;
        this.shopId = shopId;
        this.categoryName = categoryName;
        this.categoryDesc = categoryDesc;
        this.priority = priority;
        this.ctime = ctime;
        this.mtime = mtime;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getShopId() {
        return this.shopId;
    }

    public void setShopId(Long shopId) {
        this.shopId = shopId;
    }

    public String getCategoryName() {
        return this.categoryName;
    }

    public void setCategoryName(String categoryName) {
        this.categoryName = categoryName;
    }

    public String getCategoryDesc() {
        return this.categoryDesc;
    }

    public void setCategoryDesc(String categoryDesc) {
        this.categoryDesc = categoryDesc;
    }

    public Integer getPriority() {
        return this.priority;
    }

    public void setPriority(Integer priority) {
        this.priority = priority;
    }

    public Timestamp getCtime() {
        return this.ctime;
    }

    public void setCtime(Timestamp ctime) {
        this.ctime = ctime;
    }

    public Timestamp getMtime() {
        return this.mtime;
    }

    public void setMtime(Timestamp mtime) {
        this.mtime = mtime;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ProductCategoryEntity (");

        sb.append(id);
        sb.append(", ").append(shopId);
        sb.append(", ").append(categoryName);
        sb.append(", ").append(categoryDesc);
        sb.append(", ").append(priority);
        sb.append(", ").append(ctime);
        sb.append(", ").append(mtime);

        sb.append(")");
        return sb.toString();
    }
}
