/*
 * This file is generated by jOOQ.
 */
package com.jzy.order.db.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProductEntity implements Serializable {

    private static final long serialVersionUID = 439697524;

    private Long      id;
    private Long      shopId;
    private Long      categoryId;
    private String    productName;
    private String    productDesc;
    private String    productIcon;
    private String    productPic;
    private Long      price;
    private Long      stock;
    private Integer   status;
    private Integer   sellCountOneWeek;
    private Integer   sellCountOneMonth;
    private Integer   rateCountOneWeek;
    private Integer   rateCountOneMonth;
    private Timestamp ctime;
    private Timestamp mtime;

    public ProductEntity() {}

    public ProductEntity(ProductEntity value) {
        this.id = value.id;
        this.shopId = value.shopId;
        this.categoryId = value.categoryId;
        this.productName = value.productName;
        this.productDesc = value.productDesc;
        this.productIcon = value.productIcon;
        this.productPic = value.productPic;
        this.price = value.price;
        this.stock = value.stock;
        this.status = value.status;
        this.sellCountOneWeek = value.sellCountOneWeek;
        this.sellCountOneMonth = value.sellCountOneMonth;
        this.rateCountOneWeek = value.rateCountOneWeek;
        this.rateCountOneMonth = value.rateCountOneMonth;
        this.ctime = value.ctime;
        this.mtime = value.mtime;
    }

    public ProductEntity(
        Long      id,
        Long      shopId,
        Long      categoryId,
        String    productName,
        String    productDesc,
        String    productIcon,
        String    productPic,
        Long      price,
        Long      stock,
        Integer   status,
        Integer   sellCountOneWeek,
        Integer   sellCountOneMonth,
        Integer   rateCountOneWeek,
        Integer   rateCountOneMonth,
        Timestamp ctime,
        Timestamp mtime
    ) {
        this.id = id;
        this.shopId = shopId;
        this.categoryId = categoryId;
        this.productName = productName;
        this.productDesc = productDesc;
        this.productIcon = productIcon;
        this.productPic = productPic;
        this.price = price;
        this.stock = stock;
        this.status = status;
        this.sellCountOneWeek = sellCountOneWeek;
        this.sellCountOneMonth = sellCountOneMonth;
        this.rateCountOneWeek = rateCountOneWeek;
        this.rateCountOneMonth = rateCountOneMonth;
        this.ctime = ctime;
        this.mtime = mtime;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getShopId() {
        return this.shopId;
    }

    public void setShopId(Long shopId) {
        this.shopId = shopId;
    }

    public Long getCategoryId() {
        return this.categoryId;
    }

    public void setCategoryId(Long categoryId) {
        this.categoryId = categoryId;
    }

    public String getProductName() {
        return this.productName;
    }

    public void setProductName(String productName) {
        this.productName = productName;
    }

    public String getProductDesc() {
        return this.productDesc;
    }

    public void setProductDesc(String productDesc) {
        this.productDesc = productDesc;
    }

    public String getProductIcon() {
        return this.productIcon;
    }

    public void setProductIcon(String productIcon) {
        this.productIcon = productIcon;
    }

    public String getProductPic() {
        return this.productPic;
    }

    public void setProductPic(String productPic) {
        this.productPic = productPic;
    }

    public Long getPrice() {
        return this.price;
    }

    public void setPrice(Long price) {
        this.price = price;
    }

    public Long getStock() {
        return this.stock;
    }

    public void setStock(Long stock) {
        this.stock = stock;
    }

    public Integer getStatus() {
        return this.status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }

    public Integer getSellCountOneWeek() {
        return this.sellCountOneWeek;
    }

    public void setSellCountOneWeek(Integer sellCountOneWeek) {
        this.sellCountOneWeek = sellCountOneWeek;
    }

    public Integer getSellCountOneMonth() {
        return this.sellCountOneMonth;
    }

    public void setSellCountOneMonth(Integer sellCountOneMonth) {
        this.sellCountOneMonth = sellCountOneMonth;
    }

    public Integer getRateCountOneWeek() {
        return this.rateCountOneWeek;
    }

    public void setRateCountOneWeek(Integer rateCountOneWeek) {
        this.rateCountOneWeek = rateCountOneWeek;
    }

    public Integer getRateCountOneMonth() {
        return this.rateCountOneMonth;
    }

    public void setRateCountOneMonth(Integer rateCountOneMonth) {
        this.rateCountOneMonth = rateCountOneMonth;
    }

    public Timestamp getCtime() {
        return this.ctime;
    }

    public void setCtime(Timestamp ctime) {
        this.ctime = ctime;
    }

    public Timestamp getMtime() {
        return this.mtime;
    }

    public void setMtime(Timestamp mtime) {
        this.mtime = mtime;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ProductEntity (");

        sb.append(id);
        sb.append(", ").append(shopId);
        sb.append(", ").append(categoryId);
        sb.append(", ").append(productName);
        sb.append(", ").append(productDesc);
        sb.append(", ").append(productIcon);
        sb.append(", ").append(productPic);
        sb.append(", ").append(price);
        sb.append(", ").append(stock);
        sb.append(", ").append(status);
        sb.append(", ").append(sellCountOneWeek);
        sb.append(", ").append(sellCountOneMonth);
        sb.append(", ").append(rateCountOneWeek);
        sb.append(", ").append(rateCountOneMonth);
        sb.append(", ").append(ctime);
        sb.append(", ").append(mtime);

        sb.append(")");
        return sb.toString();
    }
}
