/*
 * This file is generated by jOOQ.
 */
package com.jzy.order.db.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ShopEntity implements Serializable {

    private static final long serialVersionUID = 1048797858;

    private Long      id;
    private String    name;
    private String    briefDesc;
    private Integer   allScore;
    private Integer   productScore;
    private Integer   serviceScore;
    private Integer   sellCountOneMonth;
    private Integer   rateCountOneMonth;
    private String    avatar;
    private String    pictures;
    private String    tags;
    private String    bulletin;
    private String    infos;
    private Timestamp ctime;
    private Timestamp mtime;

    public ShopEntity() {}

    public ShopEntity(ShopEntity value) {
        this.id = value.id;
        this.name = value.name;
        this.briefDesc = value.briefDesc;
        this.allScore = value.allScore;
        this.productScore = value.productScore;
        this.serviceScore = value.serviceScore;
        this.sellCountOneMonth = value.sellCountOneMonth;
        this.rateCountOneMonth = value.rateCountOneMonth;
        this.avatar = value.avatar;
        this.pictures = value.pictures;
        this.tags = value.tags;
        this.bulletin = value.bulletin;
        this.infos = value.infos;
        this.ctime = value.ctime;
        this.mtime = value.mtime;
    }

    public ShopEntity(
        Long      id,
        String    name,
        String    briefDesc,
        Integer   allScore,
        Integer   productScore,
        Integer   serviceScore,
        Integer   sellCountOneMonth,
        Integer   rateCountOneMonth,
        String    avatar,
        String    pictures,
        String    tags,
        String    bulletin,
        String    infos,
        Timestamp ctime,
        Timestamp mtime
    ) {
        this.id = id;
        this.name = name;
        this.briefDesc = briefDesc;
        this.allScore = allScore;
        this.productScore = productScore;
        this.serviceScore = serviceScore;
        this.sellCountOneMonth = sellCountOneMonth;
        this.rateCountOneMonth = rateCountOneMonth;
        this.avatar = avatar;
        this.pictures = pictures;
        this.tags = tags;
        this.bulletin = bulletin;
        this.infos = infos;
        this.ctime = ctime;
        this.mtime = mtime;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getBriefDesc() {
        return this.briefDesc;
    }

    public void setBriefDesc(String briefDesc) {
        this.briefDesc = briefDesc;
    }

    public Integer getAllScore() {
        return this.allScore;
    }

    public void setAllScore(Integer allScore) {
        this.allScore = allScore;
    }

    public Integer getProductScore() {
        return this.productScore;
    }

    public void setProductScore(Integer productScore) {
        this.productScore = productScore;
    }

    public Integer getServiceScore() {
        return this.serviceScore;
    }

    public void setServiceScore(Integer serviceScore) {
        this.serviceScore = serviceScore;
    }

    public Integer getSellCountOneMonth() {
        return this.sellCountOneMonth;
    }

    public void setSellCountOneMonth(Integer sellCountOneMonth) {
        this.sellCountOneMonth = sellCountOneMonth;
    }

    public Integer getRateCountOneMonth() {
        return this.rateCountOneMonth;
    }

    public void setRateCountOneMonth(Integer rateCountOneMonth) {
        this.rateCountOneMonth = rateCountOneMonth;
    }

    public String getAvatar() {
        return this.avatar;
    }

    public void setAvatar(String avatar) {
        this.avatar = avatar;
    }

    public String getPictures() {
        return this.pictures;
    }

    public void setPictures(String pictures) {
        this.pictures = pictures;
    }

    public String getTags() {
        return this.tags;
    }

    public void setTags(String tags) {
        this.tags = tags;
    }

    public String getBulletin() {
        return this.bulletin;
    }

    public void setBulletin(String bulletin) {
        this.bulletin = bulletin;
    }

    public String getInfos() {
        return this.infos;
    }

    public void setInfos(String infos) {
        this.infos = infos;
    }

    public Timestamp getCtime() {
        return this.ctime;
    }

    public void setCtime(Timestamp ctime) {
        this.ctime = ctime;
    }

    public Timestamp getMtime() {
        return this.mtime;
    }

    public void setMtime(Timestamp mtime) {
        this.mtime = mtime;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ShopEntity (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(briefDesc);
        sb.append(", ").append(allScore);
        sb.append(", ").append(productScore);
        sb.append(", ").append(serviceScore);
        sb.append(", ").append(sellCountOneMonth);
        sb.append(", ").append(rateCountOneMonth);
        sb.append(", ").append(avatar);
        sb.append(", ").append(pictures);
        sb.append(", ").append(tags);
        sb.append(", ").append(bulletin);
        sb.append(", ").append(infos);
        sb.append(", ").append(ctime);
        sb.append(", ").append(mtime);

        sb.append(")");
        return sb.toString();
    }
}
