/*
 * This file is generated by jOOQ.
 */
package com.jzy.order.db.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserEntity implements Serializable {

    private static final long serialVersionUID = -931356718;

    private Long      id;
    private String    uid;
    private String    password;
    private String    userName;
    private Integer   sex;
    private Integer   isAdmin;
    private String    manageShopId;
    private Timestamp ctime;
    private Timestamp mtime;

    public UserEntity() {}

    public UserEntity(UserEntity value) {
        this.id = value.id;
        this.uid = value.uid;
        this.password = value.password;
        this.userName = value.userName;
        this.sex = value.sex;
        this.isAdmin = value.isAdmin;
        this.manageShopId = value.manageShopId;
        this.ctime = value.ctime;
        this.mtime = value.mtime;
    }

    public UserEntity(
        Long      id,
        String    uid,
        String    password,
        String    userName,
        Integer   sex,
        Integer   isAdmin,
        String    manageShopId,
        Timestamp ctime,
        Timestamp mtime
    ) {
        this.id = id;
        this.uid = uid;
        this.password = password;
        this.userName = userName;
        this.sex = sex;
        this.isAdmin = isAdmin;
        this.manageShopId = manageShopId;
        this.ctime = ctime;
        this.mtime = mtime;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getUid() {
        return this.uid;
    }

    public void setUid(String uid) {
        this.uid = uid;
    }

    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getUserName() {
        return this.userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    public Integer getSex() {
        return this.sex;
    }

    public void setSex(Integer sex) {
        this.sex = sex;
    }

    public Integer getIsAdmin() {
        return this.isAdmin;
    }

    public void setIsAdmin(Integer isAdmin) {
        this.isAdmin = isAdmin;
    }

    public String getManageShopId() {
        return this.manageShopId;
    }

    public void setManageShopId(String manageShopId) {
        this.manageShopId = manageShopId;
    }

    public Timestamp getCtime() {
        return this.ctime;
    }

    public void setCtime(Timestamp ctime) {
        this.ctime = ctime;
    }

    public Timestamp getMtime() {
        return this.mtime;
    }

    public void setMtime(Timestamp mtime) {
        this.mtime = mtime;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("UserEntity (");

        sb.append(id);
        sb.append(", ").append(uid);
        sb.append(", ").append(password);
        sb.append(", ").append(userName);
        sb.append(", ").append(sex);
        sb.append(", ").append(isAdmin);
        sb.append(", ").append(manageShopId);
        sb.append(", ").append(ctime);
        sb.append(", ").append(mtime);

        sb.append(")");
        return sb.toString();
    }
}
