/*
 * This file is generated by jOOQ.
 */
package com.jzy.order.db.tables;


import com.jzy.order.db.Indexes;
import com.jzy.order.db.Keys;
import com.jzy.order.db.Order;
import com.jzy.order.db.tables.records.CommentDetailRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row9;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CommentDetail extends TableImpl<CommentDetailRecord> {

    private static final long serialVersionUID = 694823761;

    /**
     * The reference instance of <code>order.comment_detail</code>
     */
    public static final CommentDetail COMMENT_DETAIL = new CommentDetail();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CommentDetailRecord> getRecordType() {
        return CommentDetailRecord.class;
    }

    /**
     * The column <code>order.comment_detail.id</code>.
     */
    public final TableField<CommentDetailRecord, Long> ID = createField(DSL.name("id"), org.jooq.impl.SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>order.comment_detail.comment_id</code>.
     */
    public final TableField<CommentDetailRecord, Long> COMMENT_ID = createField(DSL.name("comment_id"), org.jooq.impl.SQLDataType.BIGINT.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>order.comment_detail.shop_id</code>.
     */
    public final TableField<CommentDetailRecord, Long> SHOP_ID = createField(DSL.name("shop_id"), org.jooq.impl.SQLDataType.BIGINT.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>order.comment_detail.product_id</code>.
     */
    public final TableField<CommentDetailRecord, Long> PRODUCT_ID = createField(DSL.name("product_id"), org.jooq.impl.SQLDataType.BIGINT.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>order.comment_detail.product_name</code>.
     */
    public final TableField<CommentDetailRecord, String> PRODUCT_NAME = createField(DSL.name("product_name"), org.jooq.impl.SQLDataType.VARCHAR(32).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>order.comment_detail.score</code>.
     */
    public final TableField<CommentDetailRecord, Integer> SCORE = createField(DSL.name("score"), org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>order.comment_detail.comment_content</code>.
     */
    public final TableField<CommentDetailRecord, String> COMMENT_CONTENT = createField(DSL.name("comment_content"), org.jooq.impl.SQLDataType.VARCHAR(128).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>order.comment_detail.ctime</code>.
     */
    public final TableField<CommentDetailRecord, Timestamp> CTIME = createField(DSL.name("ctime"), org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "");

    /**
     * The column <code>order.comment_detail.mtime</code>.
     */
    public final TableField<CommentDetailRecord, Timestamp> MTIME = createField(DSL.name("mtime"), org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "");

    /**
     * Create a <code>order.comment_detail</code> table reference
     */
    public CommentDetail() {
        this(DSL.name("comment_detail"), null);
    }

    /**
     * Create an aliased <code>order.comment_detail</code> table reference
     */
    public CommentDetail(String alias) {
        this(DSL.name(alias), COMMENT_DETAIL);
    }

    /**
     * Create an aliased <code>order.comment_detail</code> table reference
     */
    public CommentDetail(Name alias) {
        this(alias, COMMENT_DETAIL);
    }

    private CommentDetail(Name alias, Table<CommentDetailRecord> aliased) {
        this(alias, aliased, null);
    }

    private CommentDetail(Name alias, Table<CommentDetailRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> CommentDetail(Table<O> child, ForeignKey<O, CommentDetailRecord> key) {
        super(child, key, COMMENT_DETAIL);
    }

    @Override
    public Schema getSchema() {
        return Order.ORDER;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.COMMENT_DETAIL_COMMENT_ID, Indexes.COMMENT_DETAIL_PRIMARY, Indexes.COMMENT_DETAIL_SHOP_ID_PRODUCT_ID);
    }

    @Override
    public Identity<CommentDetailRecord, Long> getIdentity() {
        return Keys.IDENTITY_COMMENT_DETAIL;
    }

    @Override
    public UniqueKey<CommentDetailRecord> getPrimaryKey() {
        return Keys.KEY_COMMENT_DETAIL_PRIMARY;
    }

    @Override
    public List<UniqueKey<CommentDetailRecord>> getKeys() {
        return Arrays.<UniqueKey<CommentDetailRecord>>asList(Keys.KEY_COMMENT_DETAIL_PRIMARY);
    }

    @Override
    public CommentDetail as(String alias) {
        return new CommentDetail(DSL.name(alias), this);
    }

    @Override
    public CommentDetail as(Name alias) {
        return new CommentDetail(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public CommentDetail rename(String name) {
        return new CommentDetail(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public CommentDetail rename(Name name) {
        return new CommentDetail(name, null);
    }

    // -------------------------------------------------------------------------
    // Row9 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row9<Long, Long, Long, Long, String, Integer, String, Timestamp, Timestamp> fieldsRow() {
        return (Row9) super.fieldsRow();
    }
}
