/*
 * This file is generated by jOOQ.
 */
package com.jzy.order.db.tables;


import com.jzy.order.db.Indexes;
import com.jzy.order.db.Keys;
import com.jzy.order.db.Order;
import com.jzy.order.db.tables.records.ProductCategoryRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row7;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProductCategory extends TableImpl<ProductCategoryRecord> {

    private static final long serialVersionUID = 118618581;

    /**
     * The reference instance of <code>order.product_category</code>
     */
    public static final ProductCategory PRODUCT_CATEGORY = new ProductCategory();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ProductCategoryRecord> getRecordType() {
        return ProductCategoryRecord.class;
    }

    /**
     * The column <code>order.product_category.id</code>.
     */
    public final TableField<ProductCategoryRecord, Long> ID = createField(DSL.name("id"), org.jooq.impl.SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>order.product_category.shop_id</code>.
     */
    public final TableField<ProductCategoryRecord, Long> SHOP_ID = createField(DSL.name("shop_id"), org.jooq.impl.SQLDataType.BIGINT.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>order.product_category.category_name</code>.
     */
    public final TableField<ProductCategoryRecord, String> CATEGORY_NAME = createField(DSL.name("category_name"), org.jooq.impl.SQLDataType.VARCHAR(32).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>order.product_category.category_desc</code>.
     */
    public final TableField<ProductCategoryRecord, String> CATEGORY_DESC = createField(DSL.name("category_desc"), org.jooq.impl.SQLDataType.VARCHAR(64).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>order.product_category.priority</code>.
     */
    public final TableField<ProductCategoryRecord, Integer> PRIORITY = createField(DSL.name("priority"), org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>order.product_category.ctime</code>.
     */
    public final TableField<ProductCategoryRecord, Timestamp> CTIME = createField(DSL.name("ctime"), org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "");

    /**
     * The column <code>order.product_category.mtime</code>.
     */
    public final TableField<ProductCategoryRecord, Timestamp> MTIME = createField(DSL.name("mtime"), org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "");

    /**
     * Create a <code>order.product_category</code> table reference
     */
    public ProductCategory() {
        this(DSL.name("product_category"), null);
    }

    /**
     * Create an aliased <code>order.product_category</code> table reference
     */
    public ProductCategory(String alias) {
        this(DSL.name(alias), PRODUCT_CATEGORY);
    }

    /**
     * Create an aliased <code>order.product_category</code> table reference
     */
    public ProductCategory(Name alias) {
        this(alias, PRODUCT_CATEGORY);
    }

    private ProductCategory(Name alias, Table<ProductCategoryRecord> aliased) {
        this(alias, aliased, null);
    }

    private ProductCategory(Name alias, Table<ProductCategoryRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> ProductCategory(Table<O> child, ForeignKey<O, ProductCategoryRecord> key) {
        super(child, key, PRODUCT_CATEGORY);
    }

    @Override
    public Schema getSchema() {
        return Order.ORDER;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.PRODUCT_CATEGORY_PRIMARY, Indexes.PRODUCT_CATEGORY_SHOP_ID);
    }

    @Override
    public Identity<ProductCategoryRecord, Long> getIdentity() {
        return Keys.IDENTITY_PRODUCT_CATEGORY;
    }

    @Override
    public UniqueKey<ProductCategoryRecord> getPrimaryKey() {
        return Keys.KEY_PRODUCT_CATEGORY_PRIMARY;
    }

    @Override
    public List<UniqueKey<ProductCategoryRecord>> getKeys() {
        return Arrays.<UniqueKey<ProductCategoryRecord>>asList(Keys.KEY_PRODUCT_CATEGORY_PRIMARY);
    }

    @Override
    public ProductCategory as(String alias) {
        return new ProductCategory(DSL.name(alias), this);
    }

    @Override
    public ProductCategory as(Name alias) {
        return new ProductCategory(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public ProductCategory rename(String name) {
        return new ProductCategory(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ProductCategory rename(Name name) {
        return new ProductCategory(name, null);
    }

    // -------------------------------------------------------------------------
    // Row7 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row7<Long, Long, String, String, Integer, Timestamp, Timestamp> fieldsRow() {
        return (Row7) super.fieldsRow();
    }
}
