/*
 * This file is generated by jOOQ.
 */
package com.jzy.order.db.tables.records;


import com.jzy.order.db.tables.CommentDetail;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CommentDetailRecord extends UpdatableRecordImpl<CommentDetailRecord> implements Record9<Long, Long, Long, Long, String, Integer, String, Timestamp, Timestamp> {

    private static final long serialVersionUID = -1734845528;

    /**
     * Setter for <code>order.comment_detail.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>order.comment_detail.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>order.comment_detail.comment_id</code>.
     */
    public void setCommentId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>order.comment_detail.comment_id</code>.
     */
    public Long getCommentId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>order.comment_detail.shop_id</code>.
     */
    public void setShopId(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>order.comment_detail.shop_id</code>.
     */
    public Long getShopId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>order.comment_detail.product_id</code>.
     */
    public void setProductId(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>order.comment_detail.product_id</code>.
     */
    public Long getProductId() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>order.comment_detail.product_name</code>.
     */
    public void setProductName(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>order.comment_detail.product_name</code>.
     */
    public String getProductName() {
        return (String) get(4);
    }

    /**
     * Setter for <code>order.comment_detail.score</code>.
     */
    public void setScore(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>order.comment_detail.score</code>.
     */
    public Integer getScore() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>order.comment_detail.comment_content</code>.
     */
    public void setCommentContent(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>order.comment_detail.comment_content</code>.
     */
    public String getCommentContent() {
        return (String) get(6);
    }

    /**
     * Setter for <code>order.comment_detail.ctime</code>.
     */
    public void setCtime(Timestamp value) {
        set(7, value);
    }

    /**
     * Getter for <code>order.comment_detail.ctime</code>.
     */
    public Timestamp getCtime() {
        return (Timestamp) get(7);
    }

    /**
     * Setter for <code>order.comment_detail.mtime</code>.
     */
    public void setMtime(Timestamp value) {
        set(8, value);
    }

    /**
     * Getter for <code>order.comment_detail.mtime</code>.
     */
    public Timestamp getMtime() {
        return (Timestamp) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row9<Long, Long, Long, Long, String, Integer, String, Timestamp, Timestamp> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    @Override
    public Row9<Long, Long, Long, Long, String, Integer, String, Timestamp, Timestamp> valuesRow() {
        return (Row9) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return CommentDetail.COMMENT_DETAIL.ID;
    }

    @Override
    public Field<Long> field2() {
        return CommentDetail.COMMENT_DETAIL.COMMENT_ID;
    }

    @Override
    public Field<Long> field3() {
        return CommentDetail.COMMENT_DETAIL.SHOP_ID;
    }

    @Override
    public Field<Long> field4() {
        return CommentDetail.COMMENT_DETAIL.PRODUCT_ID;
    }

    @Override
    public Field<String> field5() {
        return CommentDetail.COMMENT_DETAIL.PRODUCT_NAME;
    }

    @Override
    public Field<Integer> field6() {
        return CommentDetail.COMMENT_DETAIL.SCORE;
    }

    @Override
    public Field<String> field7() {
        return CommentDetail.COMMENT_DETAIL.COMMENT_CONTENT;
    }

    @Override
    public Field<Timestamp> field8() {
        return CommentDetail.COMMENT_DETAIL.CTIME;
    }

    @Override
    public Field<Timestamp> field9() {
        return CommentDetail.COMMENT_DETAIL.MTIME;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public Long component2() {
        return getCommentId();
    }

    @Override
    public Long component3() {
        return getShopId();
    }

    @Override
    public Long component4() {
        return getProductId();
    }

    @Override
    public String component5() {
        return getProductName();
    }

    @Override
    public Integer component6() {
        return getScore();
    }

    @Override
    public String component7() {
        return getCommentContent();
    }

    @Override
    public Timestamp component8() {
        return getCtime();
    }

    @Override
    public Timestamp component9() {
        return getMtime();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public Long value2() {
        return getCommentId();
    }

    @Override
    public Long value3() {
        return getShopId();
    }

    @Override
    public Long value4() {
        return getProductId();
    }

    @Override
    public String value5() {
        return getProductName();
    }

    @Override
    public Integer value6() {
        return getScore();
    }

    @Override
    public String value7() {
        return getCommentContent();
    }

    @Override
    public Timestamp value8() {
        return getCtime();
    }

    @Override
    public Timestamp value9() {
        return getMtime();
    }

    @Override
    public CommentDetailRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public CommentDetailRecord value2(Long value) {
        setCommentId(value);
        return this;
    }

    @Override
    public CommentDetailRecord value3(Long value) {
        setShopId(value);
        return this;
    }

    @Override
    public CommentDetailRecord value4(Long value) {
        setProductId(value);
        return this;
    }

    @Override
    public CommentDetailRecord value5(String value) {
        setProductName(value);
        return this;
    }

    @Override
    public CommentDetailRecord value6(Integer value) {
        setScore(value);
        return this;
    }

    @Override
    public CommentDetailRecord value7(String value) {
        setCommentContent(value);
        return this;
    }

    @Override
    public CommentDetailRecord value8(Timestamp value) {
        setCtime(value);
        return this;
    }

    @Override
    public CommentDetailRecord value9(Timestamp value) {
        setMtime(value);
        return this;
    }

    @Override
    public CommentDetailRecord values(Long value1, Long value2, Long value3, Long value4, String value5, Integer value6, String value7, Timestamp value8, Timestamp value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CommentDetailRecord
     */
    public CommentDetailRecord() {
        super(CommentDetail.COMMENT_DETAIL);
    }

    /**
     * Create a detached, initialised CommentDetailRecord
     */
    public CommentDetailRecord(Long id, Long commentId, Long shopId, Long productId, String productName, Integer score, String commentContent, Timestamp ctime, Timestamp mtime) {
        super(CommentDetail.COMMENT_DETAIL);

        set(0, id);
        set(1, commentId);
        set(2, shopId);
        set(3, productId);
        set(4, productName);
        set(5, score);
        set(6, commentContent);
        set(7, ctime);
        set(8, mtime);
    }
}
