/*
 * This file is generated by jOOQ.
 */
package com.jzy.order.db.tables.records;


import com.jzy.order.db.tables.Shop;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record15;
import org.jooq.Row15;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ShopRecord extends UpdatableRecordImpl<ShopRecord> implements Record15<Long, String, String, Integer, Integer, Integer, Integer, Integer, String, String, String, String, String, Timestamp, Timestamp> {

    private static final long serialVersionUID = 339583921;

    /**
     * Setter for <code>order.shop.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>order.shop.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>order.shop.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>order.shop.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>order.shop.brief_desc</code>.
     */
    public void setBriefDesc(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>order.shop.brief_desc</code>.
     */
    public String getBriefDesc() {
        return (String) get(2);
    }

    /**
     * Setter for <code>order.shop.all_score</code>.
     */
    public void setAllScore(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>order.shop.all_score</code>.
     */
    public Integer getAllScore() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>order.shop.product_score</code>.
     */
    public void setProductScore(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>order.shop.product_score</code>.
     */
    public Integer getProductScore() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>order.shop.service_score</code>.
     */
    public void setServiceScore(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>order.shop.service_score</code>.
     */
    public Integer getServiceScore() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>order.shop.sell_count_one_month</code>.
     */
    public void setSellCountOneMonth(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>order.shop.sell_count_one_month</code>.
     */
    public Integer getSellCountOneMonth() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>order.shop.rate_count_one_month</code>.
     */
    public void setRateCountOneMonth(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>order.shop.rate_count_one_month</code>.
     */
    public Integer getRateCountOneMonth() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>order.shop.avatar</code>.
     */
    public void setAvatar(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>order.shop.avatar</code>.
     */
    public String getAvatar() {
        return (String) get(8);
    }

    /**
     * Setter for <code>order.shop.pictures</code>.
     */
    public void setPictures(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>order.shop.pictures</code>.
     */
    public String getPictures() {
        return (String) get(9);
    }

    /**
     * Setter for <code>order.shop.tags</code>.
     */
    public void setTags(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>order.shop.tags</code>.
     */
    public String getTags() {
        return (String) get(10);
    }

    /**
     * Setter for <code>order.shop.bulletin</code>.
     */
    public void setBulletin(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>order.shop.bulletin</code>.
     */
    public String getBulletin() {
        return (String) get(11);
    }

    /**
     * Setter for <code>order.shop.infos</code>.
     */
    public void setInfos(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>order.shop.infos</code>.
     */
    public String getInfos() {
        return (String) get(12);
    }

    /**
     * Setter for <code>order.shop.ctime</code>.
     */
    public void setCtime(Timestamp value) {
        set(13, value);
    }

    /**
     * Getter for <code>order.shop.ctime</code>.
     */
    public Timestamp getCtime() {
        return (Timestamp) get(13);
    }

    /**
     * Setter for <code>order.shop.mtime</code>.
     */
    public void setMtime(Timestamp value) {
        set(14, value);
    }

    /**
     * Getter for <code>order.shop.mtime</code>.
     */
    public Timestamp getMtime() {
        return (Timestamp) get(14);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record15 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row15<Long, String, String, Integer, Integer, Integer, Integer, Integer, String, String, String, String, String, Timestamp, Timestamp> fieldsRow() {
        return (Row15) super.fieldsRow();
    }

    @Override
    public Row15<Long, String, String, Integer, Integer, Integer, Integer, Integer, String, String, String, String, String, Timestamp, Timestamp> valuesRow() {
        return (Row15) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return Shop.SHOP.ID;
    }

    @Override
    public Field<String> field2() {
        return Shop.SHOP.NAME;
    }

    @Override
    public Field<String> field3() {
        return Shop.SHOP.BRIEF_DESC;
    }

    @Override
    public Field<Integer> field4() {
        return Shop.SHOP.ALL_SCORE;
    }

    @Override
    public Field<Integer> field5() {
        return Shop.SHOP.PRODUCT_SCORE;
    }

    @Override
    public Field<Integer> field6() {
        return Shop.SHOP.SERVICE_SCORE;
    }

    @Override
    public Field<Integer> field7() {
        return Shop.SHOP.SELL_COUNT_ONE_MONTH;
    }

    @Override
    public Field<Integer> field8() {
        return Shop.SHOP.RATE_COUNT_ONE_MONTH;
    }

    @Override
    public Field<String> field9() {
        return Shop.SHOP.AVATAR;
    }

    @Override
    public Field<String> field10() {
        return Shop.SHOP.PICTURES;
    }

    @Override
    public Field<String> field11() {
        return Shop.SHOP.TAGS;
    }

    @Override
    public Field<String> field12() {
        return Shop.SHOP.BULLETIN;
    }

    @Override
    public Field<String> field13() {
        return Shop.SHOP.INFOS;
    }

    @Override
    public Field<Timestamp> field14() {
        return Shop.SHOP.CTIME;
    }

    @Override
    public Field<Timestamp> field15() {
        return Shop.SHOP.MTIME;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public String component3() {
        return getBriefDesc();
    }

    @Override
    public Integer component4() {
        return getAllScore();
    }

    @Override
    public Integer component5() {
        return getProductScore();
    }

    @Override
    public Integer component6() {
        return getServiceScore();
    }

    @Override
    public Integer component7() {
        return getSellCountOneMonth();
    }

    @Override
    public Integer component8() {
        return getRateCountOneMonth();
    }

    @Override
    public String component9() {
        return getAvatar();
    }

    @Override
    public String component10() {
        return getPictures();
    }

    @Override
    public String component11() {
        return getTags();
    }

    @Override
    public String component12() {
        return getBulletin();
    }

    @Override
    public String component13() {
        return getInfos();
    }

    @Override
    public Timestamp component14() {
        return getCtime();
    }

    @Override
    public Timestamp component15() {
        return getMtime();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public String value3() {
        return getBriefDesc();
    }

    @Override
    public Integer value4() {
        return getAllScore();
    }

    @Override
    public Integer value5() {
        return getProductScore();
    }

    @Override
    public Integer value6() {
        return getServiceScore();
    }

    @Override
    public Integer value7() {
        return getSellCountOneMonth();
    }

    @Override
    public Integer value8() {
        return getRateCountOneMonth();
    }

    @Override
    public String value9() {
        return getAvatar();
    }

    @Override
    public String value10() {
        return getPictures();
    }

    @Override
    public String value11() {
        return getTags();
    }

    @Override
    public String value12() {
        return getBulletin();
    }

    @Override
    public String value13() {
        return getInfos();
    }

    @Override
    public Timestamp value14() {
        return getCtime();
    }

    @Override
    public Timestamp value15() {
        return getMtime();
    }

    @Override
    public ShopRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public ShopRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public ShopRecord value3(String value) {
        setBriefDesc(value);
        return this;
    }

    @Override
    public ShopRecord value4(Integer value) {
        setAllScore(value);
        return this;
    }

    @Override
    public ShopRecord value5(Integer value) {
        setProductScore(value);
        return this;
    }

    @Override
    public ShopRecord value6(Integer value) {
        setServiceScore(value);
        return this;
    }

    @Override
    public ShopRecord value7(Integer value) {
        setSellCountOneMonth(value);
        return this;
    }

    @Override
    public ShopRecord value8(Integer value) {
        setRateCountOneMonth(value);
        return this;
    }

    @Override
    public ShopRecord value9(String value) {
        setAvatar(value);
        return this;
    }

    @Override
    public ShopRecord value10(String value) {
        setPictures(value);
        return this;
    }

    @Override
    public ShopRecord value11(String value) {
        setTags(value);
        return this;
    }

    @Override
    public ShopRecord value12(String value) {
        setBulletin(value);
        return this;
    }

    @Override
    public ShopRecord value13(String value) {
        setInfos(value);
        return this;
    }

    @Override
    public ShopRecord value14(Timestamp value) {
        setCtime(value);
        return this;
    }

    @Override
    public ShopRecord value15(Timestamp value) {
        setMtime(value);
        return this;
    }

    @Override
    public ShopRecord values(Long value1, String value2, String value3, Integer value4, Integer value5, Integer value6, Integer value7, Integer value8, String value9, String value10, String value11, String value12, String value13, Timestamp value14, Timestamp value15) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ShopRecord
     */
    public ShopRecord() {
        super(Shop.SHOP);
    }

    /**
     * Create a detached, initialised ShopRecord
     */
    public ShopRecord(Long id, String name, String briefDesc, Integer allScore, Integer productScore, Integer serviceScore, Integer sellCountOneMonth, Integer rateCountOneMonth, String avatar, String pictures, String tags, String bulletin, String infos, Timestamp ctime, Timestamp mtime) {
        super(Shop.SHOP);

        set(0, id);
        set(1, name);
        set(2, briefDesc);
        set(3, allScore);
        set(4, productScore);
        set(5, serviceScore);
        set(6, sellCountOneMonth);
        set(7, rateCountOneMonth);
        set(8, avatar);
        set(9, pictures);
        set(10, tags);
        set(11, bulletin);
        set(12, infos);
        set(13, ctime);
        set(14, mtime);
    }
}
