/*
 * This file is generated by jOOQ.
 */
package com.jzy.order.db.tables.records;


import com.jzy.order.db.tables.User;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserRecord extends UpdatableRecordImpl<UserRecord> implements Record9<Long, String, String, String, Integer, Integer, String, Timestamp, Timestamp> {

    private static final long serialVersionUID = 278137569;

    /**
     * Setter for <code>order.user.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>order.user.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>order.user.uid</code>.
     */
    public void setUid(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>order.user.uid</code>.
     */
    public String getUid() {
        return (String) get(1);
    }

    /**
     * Setter for <code>order.user.password</code>.
     */
    public void setPassword(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>order.user.password</code>.
     */
    public String getPassword() {
        return (String) get(2);
    }

    /**
     * Setter for <code>order.user.user_name</code>.
     */
    public void setUserName(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>order.user.user_name</code>.
     */
    public String getUserName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>order.user.sex</code>.
     */
    public void setSex(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>order.user.sex</code>.
     */
    public Integer getSex() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>order.user.is_admin</code>.
     */
    public void setIsAdmin(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>order.user.is_admin</code>.
     */
    public Integer getIsAdmin() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>order.user.manage_shop_id</code>.
     */
    public void setManageShopId(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>order.user.manage_shop_id</code>.
     */
    public String getManageShopId() {
        return (String) get(6);
    }

    /**
     * Setter for <code>order.user.ctime</code>.
     */
    public void setCtime(Timestamp value) {
        set(7, value);
    }

    /**
     * Getter for <code>order.user.ctime</code>.
     */
    public Timestamp getCtime() {
        return (Timestamp) get(7);
    }

    /**
     * Setter for <code>order.user.mtime</code>.
     */
    public void setMtime(Timestamp value) {
        set(8, value);
    }

    /**
     * Getter for <code>order.user.mtime</code>.
     */
    public Timestamp getMtime() {
        return (Timestamp) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row9<Long, String, String, String, Integer, Integer, String, Timestamp, Timestamp> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    @Override
    public Row9<Long, String, String, String, Integer, Integer, String, Timestamp, Timestamp> valuesRow() {
        return (Row9) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return User.USER.ID;
    }

    @Override
    public Field<String> field2() {
        return User.USER.UID;
    }

    @Override
    public Field<String> field3() {
        return User.USER.PASSWORD;
    }

    @Override
    public Field<String> field4() {
        return User.USER.USER_NAME;
    }

    @Override
    public Field<Integer> field5() {
        return User.USER.SEX;
    }

    @Override
    public Field<Integer> field6() {
        return User.USER.IS_ADMIN;
    }

    @Override
    public Field<String> field7() {
        return User.USER.MANAGE_SHOP_ID;
    }

    @Override
    public Field<Timestamp> field8() {
        return User.USER.CTIME;
    }

    @Override
    public Field<Timestamp> field9() {
        return User.USER.MTIME;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getUid();
    }

    @Override
    public String component3() {
        return getPassword();
    }

    @Override
    public String component4() {
        return getUserName();
    }

    @Override
    public Integer component5() {
        return getSex();
    }

    @Override
    public Integer component6() {
        return getIsAdmin();
    }

    @Override
    public String component7() {
        return getManageShopId();
    }

    @Override
    public Timestamp component8() {
        return getCtime();
    }

    @Override
    public Timestamp component9() {
        return getMtime();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getUid();
    }

    @Override
    public String value3() {
        return getPassword();
    }

    @Override
    public String value4() {
        return getUserName();
    }

    @Override
    public Integer value5() {
        return getSex();
    }

    @Override
    public Integer value6() {
        return getIsAdmin();
    }

    @Override
    public String value7() {
        return getManageShopId();
    }

    @Override
    public Timestamp value8() {
        return getCtime();
    }

    @Override
    public Timestamp value9() {
        return getMtime();
    }

    @Override
    public UserRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public UserRecord value2(String value) {
        setUid(value);
        return this;
    }

    @Override
    public UserRecord value3(String value) {
        setPassword(value);
        return this;
    }

    @Override
    public UserRecord value4(String value) {
        setUserName(value);
        return this;
    }

    @Override
    public UserRecord value5(Integer value) {
        setSex(value);
        return this;
    }

    @Override
    public UserRecord value6(Integer value) {
        setIsAdmin(value);
        return this;
    }

    @Override
    public UserRecord value7(String value) {
        setManageShopId(value);
        return this;
    }

    @Override
    public UserRecord value8(Timestamp value) {
        setCtime(value);
        return this;
    }

    @Override
    public UserRecord value9(Timestamp value) {
        setMtime(value);
        return this;
    }

    @Override
    public UserRecord values(Long value1, String value2, String value3, String value4, Integer value5, Integer value6, String value7, Timestamp value8, Timestamp value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UserRecord
     */
    public UserRecord() {
        super(User.USER);
    }

    /**
     * Create a detached, initialised UserRecord
     */
    public UserRecord(Long id, String uid, String password, String userName, Integer sex, Integer isAdmin, String manageShopId, Timestamp ctime, Timestamp mtime) {
        super(User.USER);

        set(0, id);
        set(1, uid);
        set(2, password);
        set(3, userName);
        set(4, sex);
        set(5, isAdmin);
        set(6, manageShopId);
        set(7, ctime);
        set(8, mtime);
    }
}
