/*
 * This file is generated by jOOQ.
 */
package com.jzy.order.db;


import com.jzy.order.db.tables.Comment;
import com.jzy.order.db.tables.CommentDetail;
import com.jzy.order.db.tables.OrderDetail;
import com.jzy.order.db.tables.Orders;
import com.jzy.order.db.tables.Product;
import com.jzy.order.db.tables.ProductCategory;
import com.jzy.order.db.tables.Shop;
import com.jzy.order.db.tables.User;

import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>order</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index COMMENT_PRIMARY = Indexes0.COMMENT_PRIMARY;
    public static final Index COMMENT_SHOP_ID_UID = Indexes0.COMMENT_SHOP_ID_UID;
    public static final Index COMMENT_UK_ORDER_ID = Indexes0.COMMENT_UK_ORDER_ID;
    public static final Index COMMENT_DETAIL_COMMENT_ID = Indexes0.COMMENT_DETAIL_COMMENT_ID;
    public static final Index COMMENT_DETAIL_PRIMARY = Indexes0.COMMENT_DETAIL_PRIMARY;
    public static final Index COMMENT_DETAIL_SHOP_ID_PRODUCT_ID = Indexes0.COMMENT_DETAIL_SHOP_ID_PRODUCT_ID;
    public static final Index ORDER_DETAIL_ORDER_ID = Indexes0.ORDER_DETAIL_ORDER_ID;
    public static final Index ORDER_DETAIL_PRIMARY = Indexes0.ORDER_DETAIL_PRIMARY;
    public static final Index ORDER_DETAIL_SHOP_ID_PRODUCT_ID = Indexes0.ORDER_DETAIL_SHOP_ID_PRODUCT_ID;
    public static final Index ORDERS_ORDER_ID = Indexes0.ORDERS_ORDER_ID;
    public static final Index ORDERS_PRIMARY = Indexes0.ORDERS_PRIMARY;
    public static final Index ORDERS_SHOP_ID_UID = Indexes0.ORDERS_SHOP_ID_UID;
    public static final Index PRODUCT_PRIMARY = Indexes0.PRODUCT_PRIMARY;
    public static final Index PRODUCT_SHOP_ID_CATEGORY_ID = Indexes0.PRODUCT_SHOP_ID_CATEGORY_ID;
    public static final Index PRODUCT_CATEGORY_PRIMARY = Indexes0.PRODUCT_CATEGORY_PRIMARY;
    public static final Index PRODUCT_CATEGORY_SHOP_ID = Indexes0.PRODUCT_CATEGORY_SHOP_ID;
    public static final Index SHOP_PRIMARY = Indexes0.SHOP_PRIMARY;
    public static final Index USER_PRIMARY = Indexes0.USER_PRIMARY;
    public static final Index USER_UK_UID = Indexes0.USER_UK_UID;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index COMMENT_PRIMARY = Internal.createIndex("PRIMARY", Comment.COMMENT, new OrderField[] { Comment.COMMENT.ID }, true);
        public static Index COMMENT_SHOP_ID_UID = Internal.createIndex("shop_id_uid", Comment.COMMENT, new OrderField[] { Comment.COMMENT.SHOP_ID, Comment.COMMENT.UID }, false);
        public static Index COMMENT_UK_ORDER_ID = Internal.createIndex("uk_order_id", Comment.COMMENT, new OrderField[] { Comment.COMMENT.ORDER_ID }, true);
        public static Index COMMENT_DETAIL_COMMENT_ID = Internal.createIndex("comment_id", CommentDetail.COMMENT_DETAIL, new OrderField[] { CommentDetail.COMMENT_DETAIL.COMMENT_ID }, false);
        public static Index COMMENT_DETAIL_PRIMARY = Internal.createIndex("PRIMARY", CommentDetail.COMMENT_DETAIL, new OrderField[] { CommentDetail.COMMENT_DETAIL.ID }, true);
        public static Index COMMENT_DETAIL_SHOP_ID_PRODUCT_ID = Internal.createIndex("shop_id_product_id", CommentDetail.COMMENT_DETAIL, new OrderField[] { CommentDetail.COMMENT_DETAIL.SHOP_ID, CommentDetail.COMMENT_DETAIL.PRODUCT_ID }, false);
        public static Index ORDER_DETAIL_ORDER_ID = Internal.createIndex("order_id", OrderDetail.ORDER_DETAIL, new OrderField[] { OrderDetail.ORDER_DETAIL.ORDER_ID }, false);
        public static Index ORDER_DETAIL_PRIMARY = Internal.createIndex("PRIMARY", OrderDetail.ORDER_DETAIL, new OrderField[] { OrderDetail.ORDER_DETAIL.ID }, true);
        public static Index ORDER_DETAIL_SHOP_ID_PRODUCT_ID = Internal.createIndex("shop_id_product_id", OrderDetail.ORDER_DETAIL, new OrderField[] { OrderDetail.ORDER_DETAIL.SHOP_ID, OrderDetail.ORDER_DETAIL.PRODUCT_ID }, false);
        public static Index ORDERS_ORDER_ID = Internal.createIndex("order_id", Orders.ORDERS, new OrderField[] { Orders.ORDERS.ORDER_ID }, true);
        public static Index ORDERS_PRIMARY = Internal.createIndex("PRIMARY", Orders.ORDERS, new OrderField[] { Orders.ORDERS.ID }, true);
        public static Index ORDERS_SHOP_ID_UID = Internal.createIndex("shop_id_uid", Orders.ORDERS, new OrderField[] { Orders.ORDERS.SHOP_ID, Orders.ORDERS.UID }, false);
        public static Index PRODUCT_PRIMARY = Internal.createIndex("PRIMARY", Product.PRODUCT, new OrderField[] { Product.PRODUCT.ID }, true);
        public static Index PRODUCT_SHOP_ID_CATEGORY_ID = Internal.createIndex("shop_id_category_id", Product.PRODUCT, new OrderField[] { Product.PRODUCT.SHOP_ID, Product.PRODUCT.CATEGORY_ID }, false);
        public static Index PRODUCT_CATEGORY_PRIMARY = Internal.createIndex("PRIMARY", ProductCategory.PRODUCT_CATEGORY, new OrderField[] { ProductCategory.PRODUCT_CATEGORY.ID }, true);
        public static Index PRODUCT_CATEGORY_SHOP_ID = Internal.createIndex("shop_id", ProductCategory.PRODUCT_CATEGORY, new OrderField[] { ProductCategory.PRODUCT_CATEGORY.SHOP_ID }, false);
        public static Index SHOP_PRIMARY = Internal.createIndex("PRIMARY", Shop.SHOP, new OrderField[] { Shop.SHOP.ID }, true);
        public static Index USER_PRIMARY = Internal.createIndex("PRIMARY", User.USER, new OrderField[] { User.USER.ID }, true);
        public static Index USER_UK_UID = Internal.createIndex("uk_uid", User.USER, new OrderField[] { User.USER.UID }, true);
    }
}
