/*
 * This file is generated by jOOQ.
 */
package com.jzy.order.db;


import com.jzy.order.db.tables.Comment;
import com.jzy.order.db.tables.CommentDetail;
import com.jzy.order.db.tables.OrderDetail;
import com.jzy.order.db.tables.Orders;
import com.jzy.order.db.tables.Product;
import com.jzy.order.db.tables.ProductCategory;
import com.jzy.order.db.tables.Shop;
import com.jzy.order.db.tables.User;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Order extends SchemaImpl {

    private static final long serialVersionUID = -280816678;

    /**
     * The reference instance of <code>order</code>
     */
    public static final Order ORDER = new Order();

    /**
     * The table <code>order.comment</code>.
     */
    public final Comment COMMENT = com.jzy.order.db.tables.Comment.COMMENT;

    /**
     * The table <code>order.comment_detail</code>.
     */
    public final CommentDetail COMMENT_DETAIL = com.jzy.order.db.tables.CommentDetail.COMMENT_DETAIL;

    /**
     * The table <code>order.order_detail</code>.
     */
    public final OrderDetail ORDER_DETAIL = com.jzy.order.db.tables.OrderDetail.ORDER_DETAIL;

    /**
     * The table <code>order.orders</code>.
     */
    public final Orders ORDERS = com.jzy.order.db.tables.Orders.ORDERS;

    /**
     * The table <code>order.product</code>.
     */
    public final Product PRODUCT = com.jzy.order.db.tables.Product.PRODUCT;

    /**
     * The table <code>order.product_category</code>.
     */
    public final ProductCategory PRODUCT_CATEGORY = com.jzy.order.db.tables.ProductCategory.PRODUCT_CATEGORY;

    /**
     * The table <code>order.shop</code>.
     */
    public final Shop SHOP = com.jzy.order.db.tables.Shop.SHOP;

    /**
     * The table <code>order.user</code>.
     */
    public final User USER = com.jzy.order.db.tables.User.USER;

    /**
     * No further instances allowed
     */
    private Order() {
        super("order", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Comment.COMMENT,
            CommentDetail.COMMENT_DETAIL,
            OrderDetail.ORDER_DETAIL,
            Orders.ORDERS,
            Product.PRODUCT,
            ProductCategory.PRODUCT_CATEGORY,
            Shop.SHOP,
            User.USER);
    }
}
